import assert from "node:assert/strict";
import { HERITAGE_CATALOG, HERITAGE_CATALOG_VERSION, heritageCatalogItem, heritageCatalogStats } from "./heritage-catalog.mjs";
assert.equal(HERITAGE_CATALOG_VERSION, "heritage365-catalog-v1.0-static-whc-verified");
assert.equal(HERITAGE_CATALOG.length, 365);
assert.deepEqual(HERITAGE_CATALOG.map(x=>x.day), Array.from({length:365},(_,i)=>i+1));
assert.equal(new Set(HERITAGE_CATALOG.map(x=>String(x.unescoId))).size, 365);
assert.ok(HERITAGE_CATALOG.every(x=>x.fixed === true));
assert.ok(HERITAGE_CATALOG.every(x=>x.unescoId && x.unescoUrl && x.year && x.category && Array.isArray(x.criteria) && x.criteria.length));
assert.equal(heritageCatalogItem(1).unescoId, "326");
assert.equal(heritageCatalogItem(6).unescoId, "668");
assert.equal(heritageCatalogItem(7).titleEn, "Tasmanian Wilderness");
assert.equal(heritageCatalogItem(365).unescoId, "829");
const stats=heritageCatalogStats(); assert.equal(stats.count,365); assert.equal(stats.uniqueIds,365); assert.ok(stats.countries>=100);
for(let i=0;i<HERITAGE_CATALOG.length;i++) for(let j=i+1;j<Math.min(HERITAGE_CATALOG.length,i+6);j++) assert.notEqual(HERITAGE_CATALOG[i].countryEn,HERITAGE_CATALOG[j].countryEn,`country repeat too close days ${i+1}/${j+1}`);
console.log("heritage catalog: ok", stats);
