import assert from "node:assert/strict";
import fs from "node:fs";
import {DAILY_DELIVERY_SLOTS,independentJobsForTick,runIndependentJob} from "./worker.source.mjs";
const src=fs.readFileSync(new URL("./worker.source.mjs",import.meta.url),"utf8");
assert.equal(DAILY_DELIVERY_SLOTS.length,10,"official daily slot count must be 10");
assert.equal(DAILY_DELIVERY_SLOTS.some(s=>s.time==="09:30"||s.postType==="weather"||s.id==="weather_0930"),false,"Weather slot must not exist in Daily Health/Scheduler");
assert.match(src,/const WEATHER_PRODUCTION_DISABLED = true/);
assert.doesNotMatch(src,/add\("weather-scan"/);
assert.doesNotMatch(src,/add\("weather-final"/);
assert.match(src,/case "weather_scan": return \{ disabled:true/);
assert.match(src,/case "weather_final": return \{ disabled:true/);
assert.doesNotMatch(src,/new Set\(\["morning", "weather"/);
assert.doesNotMatch(src,/\["[^\n]*09:30", "weather"\]/);
assert.match(src,/async function adminWeatherManage\(env, action\) \{\s*return \{ok:true,disabled:true/s);
assert.match(src,/\["\/weather","\/weather_prepare","\/weather_status","\/weather_preview"\]\.includes\(command\)/);
assert.match(src,/هیچ Scan، Prepare، Finalize یا تغییری در State آب‌وهوا انجام نشد/);
console.log("weather-disabled.contract: PASS");
